### ISSUE TITLE
Positioning of morphs within the window

### ISSUE THREAD

**Issue by jigyasa-grover** [jig08/sQuick_new#19]
Basically, positioning of `box` within `boxWindow` would do the trick, as the rest are set inside `box` morph itself.

**Comment by jigyasa-grover** [comment]
## Steps to reproduce:
1.  Open a fresh image
2. _Load Configuration_ : `World` > `Tools` > `Configuration Browser` > `sQuick_new` 
3. Do It `IndexInterface open` in playground

The following screen opens up:
![screenshot from 2015-08-10 19 39 49](https://cloud.githubusercontent.com/assets/9291400/9176296/2db753a8-3fa8-11e5-8f7f-ea98cc286a7d.png)

Whereas, it is desired that the `box` ImageMorph be center aligned in `boxWindow` as:

![screenshot from 2015-07-30 19-44-08](https://cloud.githubusercontent.com/assets/9291400/9176565/b095fe0e-3fa9-11e5-9a10-22eec592f4e9.png)

**Comment by seandenigris** [comment]
Very nice! You provided a clear path to help :) It inspired me to take a look… Centering something in a window seems like a normal enough task, but I too had trouble, so I gave up. Instead of tweaking the window directly, just put `box` in a parent Morph that's configured the way you want, and then put _that_ in a window. For example:

```
    panel := Morph new
        color: Color black;
        changeTableLayout;
        wrapCentering: #center;
        addMorph: box;
        yourself.
    boxWindow := panel openInWindow.
    boxWindow setLabel: 'searchQuick'.
    box position: 150@0.
    boxWindow fullscreen.
```

N.B. you do not have to do `boxWindow addMorph:`. This is already done via `openInWindow`. Also, you probably don't want to set the window's `color:` directly, because a window is a Morph, so that sets the entire thing black, not just the contents.

**Comment by jigyasa-grover** [comment]
@seandenigris 
Thank You Sir :)
I am just trying to follow your steps, long way way to go though.

And, yes I tried using the above suggested method and it works perfectly. I have pushed the code and am closing this issue as it seems to have been resolved.
Thanks for the help .
