### ISSUE TITLE
Removal of "OK" & "CANCEL" buttons from Accordion Widget (PopUp)

### ISSUE THREAD

**Issue by jigyasa-grover** [jig08/sQuick_new#24]

**Comment by jigyasa-grover** [comment]
Only keeping the **BACK** bar at the bottom.
No **OK** and **CANCEL** buttons.

**Comment by jigyasa-grover** [comment]
# Steps to reproduce:
1. Open a fresh image
2. Load Configuration : `World` > `Tools` > `Configuration Browser` > `sQuick_new`
3. Do It `IndexInterface open` in playground.
4. Type a search string, say **help** and click on `Search` button.
5. An _accordion_ widget (made using `WidgetExamples exampleBuilder>>#newPluggableDialogWindow` opens up showing expandable search results.

The main aim is to remove the **OK** and **CANCEL** buttons set by default in `PluggableDialogWindow`.

![screenshot from 2015-08-16 00 25 17](https://cloud.githubusercontent.com/assets/9291400/9290384/5e348640-43ae-11e5-888e-5c8878831a47.png)

**Comment by jigyasa-grover** [comment]
@seandenigris
I tried inserting `dialog buttons: nil.` to get the desired effect but in vain.

**Comment by seandenigris** [comment]
Okay, great job on the reproducible steps! I was able to get right to work.

Now, on to the more important point - the difference between a novice and master programmer is not not-getting-stuck; it's getting unstuck quickly. Let's talk a bit about that workflow...

A pro tip for when your bug is embedded in complex code, as this one is, is to create a simple example to recreate it. For example:

```
dialog := WidgetExamples exampleBuilder newPluggableDialogWindow: 'SEARCH  RESULTS  FOR'.
dialog openFullscreen.
```

The above does _not_ have okay and cancel buttons, so something you're doing must be adding them. This is already an important realization...

Now you have two options:
1. Add your customizations to the simple example until you reproduce the error
2. Selectively comment out your code, moving it closer and closer to the simple example, until the error disappears

Using #2 as an example, if we apply selective commenting to different sections of `Popup>>printSearchResults`, we find that the problem is specifically:

```
dialog model: nil.
"followed by"
dialog buttons: nil.
```

If you comment out the #model: send, the buttons disappear, if you move the #buttons: send before the #model: send, you actually have to change the statement to `dialog buttons: {}`, but again the buttons disappear.

So, when a problem arises, it is absolutely crucial not - as we all are prone to do - to get frustrated and flop around making random changes, but to apply a rigorous process of narrowing down the offending code.

**Comment by jigyasa-grover** [comment]
@seandenigris 
Many thanks for your kind help and the Pro-tip :smiley: 
Will keep in mind the suggestions and work upon them to resolve such issues smoothly in future.

**Comment by jigyasa-grover** [comment]
Issue resolved by modifying `dialog buttons: nil` to `dialog buttons: {}` and inserting it before `dialog model: nil` code line.

![screenshot from 2015-08-19 16 25 31](https://cloud.githubusercontent.com/assets/9291400/9354556/f0bcccba-468e-11e5-8892-bb927b8852ab.png)
